[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
rev = 'next'
hook_add = '''
  let g:LanguageClient_serverCommands = {
    \ 'vue': ['vls'],
    \ 'd': ['~/.dub/packages/.bin/dls-latest/dls'],
    \}
  nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
  nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
  nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
'''
# vls = 'node vue-language-server'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#auto_complete_start_length = 1

  inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
  inoremap <expr><s-tab> pumvisible() ? "<C-p>" : "<C-h>"
'''

# Snippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Template
[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
  let g:sonictemplate_vim_template_dir = [
  \ '$HOME/.config/nvim/templates'
  \ ]
'''

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \  'colorscheme' : 'Tomorrow_Night',
  \}
'''

# file
[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
  nnoremap <Space>f :Vaffle %:h<CR>
'''

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# Color scheme
[[plugins]]
repo = 'morhetz/gruvbox'
